version: "3"

# IMPORTANT
# Make sure you run setup-docker.sh before executing this!!!
#
# Bump the client image version HERE when changing client/Dockerfile

services:
  runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
      - elasticsearch
      - mysql
      - postgres
    links:
      - mongodb
      - elasticsearch
      - mysql
      - postgres
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
     - ./.docker_node_modules:/usr/src/app/node_modules:Z
    command: sh -c 'tail -f /dev/null'

  mongodb:
    image: 'mongo:3.2.17'
    ports:
      - "27017:27017"
    expose:
      - 27017

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  elasticsearch:
    image: elasticsearch:6.4.1
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']